---
title: Trada Tech
timezone: UTC
collections:
  bitcoin:
    title: Bitcoin
    output: true
  posts:
    title: Posts
    output: true
  teddy:
    title: Teddy
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    image: "/assets/img/trada_cover.png"
    category: blog
    author: thi
- scope:
    path: ''
    type: pages
  values:
    image: "/assets/img/trada_cover.png"
lang: vi
description: Hiểu đúng làm thực blockchain.
baseurl: "/"
url: https://trada.tech
google_analytics: UA-8597504-5
markdown: kramdown
theme: minima
show_excerpts: true
author: thi
logo: "/assets/img/trada_cover.png"
facebook:
  app_id: 2178421482485741
  publisher: https://facebook.com/tradatech
plugins:
- jekyll-feed
prose:
  siteurl: 'http://trada.tech/'
  media: '_uploads'
